from mistralai import Mistral

def query_mistral(user_input: str, history: list[str], api_key: str) -> str:
    """
    Queries the Mistral model by sending a request with a conversation history.

    Args:
        user_input (str): The question or input text to send to the model.
        history (list[str]): List of previous messages in the conversation.
        api_key (str): The API key to access the Mistral model.

    Returns:
        str: The response generated by the model.
    """
    
    # Configure the API and model
    model = "mistral-large-latest"
    
    # Initialize the Mistral client with the API key
    client = Mistral(api_key=api_key)
    
    # Use the last 5 messages from the conversation for better context
    conversation_history = "\n".join(history[-5:])
    prompt = f"{conversation_history}\nYou: {user_input}\nBot:"

    try:
        # Send the request to the model
        response = client.chat.complete(   
            model=model,  
            messages=[{"role": "user", "content": prompt}], 
            max_tokens=150,  # Limit the length of the response
            temperature=0.7,  # Control the creativity of the response
            top_p=0.9,  # Filter the response by cumulative probability
        )
        
        # Return the content of the generated response
        return response.choices[0].message.content

    except Exception as e:
        # Handle errors with a detailed message
        print(f"Detailed error: {e}")
        return "Sorry, an error occurred while processing your request."
